# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desktop_assistantUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.bot_templete = QtWidgets.QLabel(self.centralwidget)
        self.bot_templete.setGeometry(QtCore.QRect(220, 120, 311, 481))
        self.bot_templete.setText("")
        self.bot_templete.setPixmap(QtGui.QPixmap("G.U.I Material/Background/bot_templete.gif"))
        self.bot_templete.setScaledContents(True)
        self.bot_templete.setObjectName("bot_templete")
        
        self.system_online = QtWidgets.QLabel(self.centralwidget)
        self.system_online.setGeometry(QtCore.QRect(520, 140, 261, 151))
        self.system_online.setText("")
        self.system_online.setPixmap(QtGui.QPixmap("G.U.I Material/Background/system_online.gif"))
        self.system_online.setScaledContents(True)
        self.system_online.setObjectName("system_online")
        
        self.smart_match = QtWidgets.QLabel(self.centralwidget)
        self.smart_match.setGeometry(QtCore.QRect(0, 250, 301, 351))
        self.smart_match.setText("")
        self.smart_match.setPixmap(QtGui.QPixmap("G.U.I Material/Background/smart_match.gif"))
        self.smart_match.setScaledContents(True)
        self.smart_match.setObjectName("smart_match")
        
        self.RUN = QtWidgets.QPushButton(self.centralwidget)
        self.RUN.setGeometry(QtCore.QRect(10, 520, 71, 31))
        self.RUN.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.RUN.setObjectName("RUN")
        
        self.TERMINATE = QtWidgets.QPushButton(self.centralwidget)
        self.TERMINATE.setGeometry(QtCore.QRect(90, 520, 121, 31))
        self.TERMINATE.setStyleSheet("background-color: rgb(85, 255, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 0, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.TERMINATE.setObjectName("TERMINATE")
        
        self.initialgif = QtWidgets.QLabel(self.centralwidget)
        self.initialgif.setGeometry(QtCore.QRect(0, 0, 291, 121))
        self.initialgif.setText("")
        self.initialgif.setPixmap(QtGui.QPixmap("G.U.I Material/Background/initial.gif"))
        self.initialgif.setScaledContents(True)
        self.initialgif.setObjectName("initialgif")
        
        self.Code_Templete = QtWidgets.QLabel(self.centralwidget)
        self.Code_Templete.setGeometry(QtCore.QRect(0, 20, 311, 301))
        self.Code_Templete.setText("")
        self.Code_Templete.setPixmap(QtGui.QPixmap("G.U.I Material/Background/Code_Template.gif"))
        self.Code_Templete.setObjectName("Code_Templete")
        
        self.Earth_Templete = QtWidgets.QLabel(self.centralwidget)
        self.Earth_Templete.setGeometry(QtCore.QRect(290, 0, 231, 121))
        self.Earth_Templete.setText("")
        self.Earth_Templete.setPixmap(QtGui.QPixmap("G.U.I Material/Background/Earth_Template.gif"))
        self.Earth_Templete.setScaledContents(True)
        self.Earth_Templete.setObjectName("Earth_Templete")
        
        self.Jarvis_Gui = QtWidgets.QLabel(self.centralwidget)
        self.Jarvis_Gui.setGeometry(QtCore.QRect(520, 0, 261, 141))
        self.Jarvis_Gui.setText("")
        self.Jarvis_Gui.setPixmap(QtGui.QPixmap("G.U.I Material/Background/Jarvis_Gui (1).gif"))
        self.Jarvis_Gui.setScaledContents(True)
        self.Jarvis_Gui.setObjectName("Jarvis_Gui")
        
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(250, 530, 221, 21))
        self.progressBar.setMinimumSize(QtCore.QSize(221, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.progressBar.setStyleSheet("color: rgb(85, 170, 127);")
        self.progressBar.setProperty("value", 50)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        
        self.WatsApp = QtWidgets.QPushButton(self.centralwidget)
        self.WatsApp.setGeometry(QtCore.QRect(10, 560, 101, 31))
        self.WatsApp.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 255, 127);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.WatsApp.setObjectName("WatsApp")
        
        self.Google = QtWidgets.QPushButton(self.centralwidget)
        self.Google.setGeometry(QtCore.QRect(340, 560, 101, 31))
        self.Google.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.Google.setObjectName("Google")
        
        self.Facebook = QtWidgets.QPushButton(self.centralwidget)
        self.Facebook.setGeometry(QtCore.QRect(120, 560, 101, 31))
        self.Facebook.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(0, 85, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.Facebook.setObjectName("Facebook")
        
        self.YouTube = QtWidgets.QPushButton(self.centralwidget)
        self.YouTube.setGeometry(QtCore.QRect(230, 560, 101, 31))
        self.YouTube.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(255, 85, 0);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.YouTube.setObjectName("YouTube")
        
        self.standing_bot = QtWidgets.QLabel(self.centralwidget)
        self.standing_bot.setGeometry(QtCore.QRect(490, 280, 291, 321))
        self.standing_bot.setText("")
        self.standing_bot.setPixmap(QtGui.QPixmap("G.U.I Material/Background/standing_bot.gif"))
        self.standing_bot.setScaledContents(True)
        self.standing_bot.setObjectName("standing_bot")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RUN.setText(_translate("MainWindow", "RUN"))
        self.TERMINATE.setText(_translate("MainWindow", "TERMINATE"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.WatsApp.setText(_translate("MainWindow", "Wats App"))
        self.Google.setText(_translate("MainWindow", "Google"))
        self.Facebook.setText(_translate("MainWindow", "Facebook"))
        self.YouTube.setText(_translate("MainWindow", "YouTube"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
